### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ahmadnajar10** [nickbutcher/plaid#109] opened 2016-08-30 13:54 UTC
Error:(32, 0) For input string: ""
>Open File</a>

**Comment by nickbutcher** [comment] 2016-08-30 13:57
Please can you provide more info, I don't understand the issue you are having??

**Comment by ahmadnajar10** [comment] 2016-08-30 13:59
i download the project when i add it to android studio and i tried to sync it give's me this error

**Comment by ahmadnajar10** [comment] 2016-08-30 14:00
and its exactly in this line def gitCommitCount = 100 +
        Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim()) i dont understand what dose it mean

**Comment by nickbutcher** [comment] 2016-08-30 14:03
As explained in the comment in the line above, this is executing a Git command to query the git SHA, latest tag and commit count, which it then uses to automate version numbers.

Building Plaid requires git on your path; closing as dupe of #17.

**Closed by nickbutcher** 2016-08-30 14:03 UTC
