### ISSUE TITLE
Error:For input string: ""

### ISSUE THREAD

**Issue by jp1017** [nickbutcher/plaid#112] opened 2016-08-31 01:13 UTC
Open project with Android Studio, logcat show: ------- Error:For input string: ""

**Comment by YuGoal** [comment] 2016-08-31 06:48
I also encountered the same problem

**Comment by YuGoal** [comment] 2016-08-31 06:49
I also encountered the same problem

**Comment by hanqingkai** [comment] 2016-09-07 03:48
删除
def gitCommitCount = 100 +
Integer.parseInt("git --git-dir=${projectDir}/.git --work-tree=${projectDir} rev-list --count HEAD".execute().text.toInteger())
和
versionCode gitCommitCount就可以了

**Comment by nickbutcher** [comment] 2016-09-07 09:47
Building Plaid requires git on your path (to automate versioning); closing as dupe of #17.

**Closed by nickbutcher** 2016-09-07 09:47 UTC
