### ISSUE TITLE
could not be compiled

### ISSUE THREAD

**Issue by wanyt** [nickbutcher/plaid#108] opened 2016-08-14 11:41 UTC
when i import the project into anroid studio in the first time, it report the error:
Error:(29, 0) CreateProcess error=2, 系统找不到指定的文件。
<a href="openFile:E:\AndroidStudio\GitHub\plaid\app\build.gradle">Open File</a>

the error occured in the build.gradle, "def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()" 

系统找不到指定的文件 --> The system could not find the file specified

**Comment by hotchemi** [comment] 2016-08-14 12:07
@wanyt I guess you didn't clone but just download source right? It seems like shows the error which is related to execute git command.

**Comment by wanyt** [comment] 2016-08-15 01:10
@hotchemi In fact, I clone but not download source.

**Comment by nickbutcher** [comment] 2016-08-15 07:21
Building requires git on your path (to help automate versioning). Closing as dupe of #17.

**Closed by nickbutcher** 2016-08-15 07:21 UTC
