### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by sergeyfitis** [nickbutcher/plaid#146] opened 2016-11-23 11:59 UTC
Nexus 5, API 23
![img](https://dl2.pushbulletusercontent.com/Cak62MX0tYgn2tguRMzUAsGaRpWrmnZw/Screenshot_20161123-135505.png)

**Comment by nickbutcher** [comment] 2016-11-23 15:24
Thanks for the issue report but this looks like a dupe of #142.

**Closed by nickbutcher** 2016-11-23 15:24 UTC
