### ISSUE TITLE
Opening DribbbleShot for second time problem with image loading

### ISSUE THREAD

**Issue by ShkurtiA** [nickbutcher/plaid#2] opened 2015-10-30 23:58 UTC
Hello,
Thanks for this great source code :)

There is a problem when I open DesignerNewsStory for second time for an item in recycler view. I have made two screenshots for the first time and for the second time.

![screenshot_2015-10-31-00-25-36](https://cloud.githubusercontent.com/assets/8733915/10860368/4bdb33fa-7f67-11e5-901c-2e99bc0c0e40.png)

![screenshot_2015-10-31-00-25-43](https://cloud.githubusercontent.com/assets/8733915/10860366/43567140-7f67-11e5-9700-2575f068a055.png)

Each time I open them I get this in my log:

10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette: Exception thrown during async generate
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at android.graphics.Bitmap.checkPixelsAccess(Bitmap.java:1390)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at android.graphics.Bitmap.getPixels(Bitmap.java:1346)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at android.support.v7.graphics.Palette$Builder.getPixelsFromBitmap(Palette.java:693)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at android.support.v7.graphics.Palette$Builder.generate(Palette.java:607)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at android.support.v7.graphics.Palette$Builder$1.doInBackground(Palette.java:664)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at android.support.v7.graphics.Palette$Builder$1.doInBackground(Palette.java:660)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-31 00:25:38.821 26818-3395/io.plaidapp E/Palette:     at java.lang.Thread.run(Thread.java:818)

It is running in Android Api 21.

Thanks

**Comment by lzanita09** [comment] 2015-10-31 17:16
Seems like the problem was in the Palette builder's `setRegion` method call in `DribbbleShot`. `regionWidth` is one pixel larger than `bitmapWidth`.

In `Palette#generate()`, a scaled down version of the bitmap is generated with Math.round() width, and then later on the region is generated using Math.floor() left and Math.ceiling() right, making the region one pixel larger than the width of the bitmap.

**Comment by chrisbanes** [comment] 2015-11-02 09:54
https://code.google.com/p/android/issues/detail?id=191013

**Comment by nickbutcher** [comment] 2015-11-13 12:00
Thanks for investigating @lzanita09.  This should be resolved by 90c7077626575e3660721af7b3e21a818e9215f7 which includes the palette fix.  As I've not been able to replicate this, please can someone verify before we close this issue? Thanks!

**Comment by lzanita09** [comment] 2015-11-13 14:49
@nickbutcher Confirmed, the issue is fixed.

**Comment by ravikumar-n** [comment] 2015-11-13 19:32
@lzanita09 @chrisbanes  I have tested this issue in latest build `supportLibVersion = '23.1.1'` in Moto-G Lolliop-5.1(API-22), it doesn't seem to fix the issue.

**Comment by lzanita09** [comment] 2015-11-13 20:31
@ravikumar-n @nickbutcher I take that back, the issue still exists. I was using `bitmap.getWidth() - 1` on my fork so that the width isn't exceeding the region width, but the problem with Palette seems still be there.

**Comment by nickbutcher** [comment] 2015-11-18 12:29
Confirmed, i'm still seeing this error in the logs with Palette 23.1.1. I've pushed a workaround until this issue is resolved. cc/ @chrisbanes

**Comment by chrisbanes** [comment] 2015-11-18 15:16
I've opened an internal bug to remind to have a look.

**Closed** 2017-10-27 11:53 UTC
