### ISSUE TITLE
Gradle sync failed: For input string: ""Consult IDE log for more details (Help | Show Log) (1s 903ms)

### ISSUE THREAD

**Issue by Rameshkumarpolavarapu** [nickbutcher/plaid#229] opened 2017-11-03 08:13 UTC
def gitCommitCount = 100 +
Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())

**Comment by nickbutcher** [comment] 2017-11-03 10:44
You need to have git on your path. Closing as dupe of #17

**Closed by nickbutcher** 2017-11-03 10:44 UTC
