### ISSUE TITLE
error while importing via Android-Studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [nickbutcher/plaid#17] opened 2015-11-01 23:29 UTC
this is what I get :
![untitled20151102012902](https://cloud.githubusercontent.com/assets/5357526/10872010/332077c6-8101-11e5-9de5-3b860db2dadc.png)

**Comment by littledot** [comment] 2015-11-02 05:46
I tried building this on Windows and faced the same issue. To build, I had to...
* Remove dependency to `git`
```groovy
// query git for the the SHA, Tag and commit count. Use these to automate versioning.
//def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()
//def gitTag = 'git describe --tags'.execute([], project.rootDir).text.trim()
//def gitCommitCount =
//        Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())
def gitSha = 'a'
def gitTag = 'a'
def gitCommitCount = 1
```
* Set Android Studio to `use default Gradle wrapper (recommended)` in `Settings > Search 'gradle' > Gradle`

To get `./gradlew build` to work in Windows, I had to additionally disable lint
* Ignore XML errors in `app` and `third_party/bypass`
```groovy
    lintOptions{
        abortOnError false
    }
```

**Comment by AndroidDeveloperLB** [comment] 2015-11-02 06:16
Why does it matter that it's on Windows?
Android-Studio should work fine on all OSs...

**Comment by Poonjaroen** [comment] 2015-11-02 09:16
I error when import 

Error : (22,0) For input String : ""
                     Open File

when click Open File

show Error line

def gitCommitCount = Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())

**Comment by qmar** [comment] 2015-11-02 14:30
Use git do download this repository, it should be fine then. Otherwise just change this line to 
`def gitCommitCount = 5`

**Comment by littledot** [comment] 2015-11-02 18:47
I'm merely sharing what worked for me. If it doesn't work for you then too bad.

**Comment by tailanx** [comment] 2015-11-03 03:33
Error:(23, 0) For input string: ""


def gitCommitCount = Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())
 what's result？？

**Comment by rekire** [comment] 2015-11-03 06:30
This seems to take some information from the git system might be the tag or branch. This error just happens if the git command is not in your environment variable.

**Comment by nevack** [comment] 2015-11-04 18:02
Just add git\bin to PATH variable. Fixed for me.

**Comment by nickbutcher** [comment] 2015-11-11 14:16
Sorry for the slow reply here. Yes the build uses git to automate the version number (based on the number of commits) and version name (based on the latest git tag). You therefore need to have git on your path.  Closing this as working as intended.

**Closed by nickbutcher** 2015-11-11 14:16 UTC

**Comment by AndroidDeveloperLB** [comment] 2015-11-11 22:40
@nickbutcher Still can't import as normal, not even via TortoiseGit. Here's what I get after importing the cloned project:
![untitled20151112004001](https://cloud.githubusercontent.com/assets/5357526/11105181/f6b3f8c6-88d5-11e5-978d-b9b3fa692e37.png)


I don't understand what's with the automation. Why is it needed?

**Comment by nickbutcher** [comment] 2015-11-13 11:40
The automation makes it easier for me to upload to Google Play which requires an increasing version code per build.

**Comment by AndroidDeveloperLB** [comment] 2015-11-13 11:46
But this also makes it impossible to import the project for some reason. 
Why is this issue closed ?

**Comment by rekire** [comment] 2015-11-13 12:19
In short you need to fix your environment to make this work. As already pointed out you need to have the path of your git executable in your environment variable.

**Comment by AndroidDeveloperLB** [comment] 2015-11-13 14:16
What's wrong with my environment ? I've already imported a lot of projects and never had this issue.
Also, git is already used, as this is how I've cloned the repo. I don't understand why I need to do it all, and how it could even help

**Comment by BillBosiolis** [comment] 2015-11-13 23:02
On Ubuntu, with Git installed (and being on the path) I had no problem to open the project in Android Studio and build it successfully.

On Windows, I was getting the known error (20 - CreateProcess error=2). Here's what I did to solve it

1. Installed a newer Git version (I don't think it has to do anything with the version, I just wanted to modify the installation)
2. In the "Adjusting your Path environment" step I selected the second option - Run Git from the Windows Command Prompt
3. Restarted Studio and set the the path to the git executable. Settings -> Version Control -> Git and set it "C:\Program Files\Git\cmd\git.exe".

Hope that it helps

**Comment by adityanaik** [comment] 2015-12-14 05:05
Environment Variables > System Variables > Select "PATH" > Click Edit > Paste *;C:\Program Files\Git\bin;C:\Program Files\Git\cmd*
Your install location may vary.

**Comment by AndroidDeveloperLB** [comment] 2015-12-14 22:07
@adityanaik This doesn't make sense, because the IDE can already clone any other Github repo.

**Comment by adityanaik** [comment] 2015-12-15 04:22
@AndroidDeveloperLB ok, but it wasn't happening for me on Windows 8.1 even after *git clone*. May be because my Git client (the one from git-scm.com) didn't set its path in environment variables during installation. And I wasn't aware of this because I was using Git Bash for my commits, not cmd. The auto-increment-versionNumber hack is awesome though. :)

**Comment by AndroidDeveloperLB** [comment] 2015-12-16 11:45
Why is this issue closed? I still can't import it.
Here's what I see now:

![untitled20151216134532](https://cloud.githubusercontent.com/assets/5357526/11840045/55bdd914-a3fb-11e5-96cf-9fb670920521.png)

**Comment by adityanaik** [comment] 2015-12-16 12:14
@AndroidDeveloperLB I was getting the exact same error - weird why it's not working for you. *git clone* it, and check if the "PATH" under Environment Variables is correct.

**Comment by codeversed** [comment] 2017-10-18 13:50
A workaround for the git rev-list command not working in Gradle is the following:

`def gitCommitCount = Integer.parseInt(['sh', '-c', 'git rev-list HEAD | wc -l | tr -d " "'].execute([], project.rootDir).text.trim())`

**Comment by vinhnguyenitvn** [comment] 2019-03-24 10:48
> A workaround for the git rev-list command not working in Gradle is the following:
> 
> `def gitCommitCount = Integer.parseInt(['sh', '-c', 'git rev-list HEAD | wc -l | tr -d " "'].execute([], project.rootDir).text.trim())`

This works for me. 
I'm using MacOS, and I'm sure I cloned project with Git, and Git is in my PATH

**Comment by AndroidDeveloperLB** [comment] 2019-03-24 19:42
Why not just fix the repository so that all could try it out without any special workarounds?
