### ISSUE TITLE
Error:(29, 0) CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by Zild95** [nickbutcher/plaid#90] opened 2016-05-21 10:48 UTC
As I try to load the project into AS and auto sync with Gradle it gives ne error as stated above. I've tried clean and re run the project, even disable plugin and restart AS, it keeps show the same error.

Error at line 29 app/build.gradle;
**def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()**

**Comment by nickbutcher** [comment] 2016-05-23 09:38
Sounds like you don't have git on your path?

**Comment by gabrieljuan** [comment] 2016-05-23 10:35
I got a same error, I just download the zip and load it using android studio. I have git, with sourcetree as its client. Should I add the project to my git?

**Comment by Zild95** [comment] 2016-05-23 11:49
@nickbutcher I don't have Git in PATH variable environment? But I have GitHub installed and as I follow this tutorial,[http://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows]
and went to directory they tell, **;C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd**
were not found too in my PC.
What setup do I miss for your project..?
I only have Android Studio, Android SDK, Android AVD, and GitHub for Desktop installed.

**Comment by shinayser** [comment] 2016-05-24 14:22
Same problem here. I downloaded the zip, opened on Studio and got that error.

**Comment by fiasko131** [comment] 2016-05-25 06:29
same here

**Comment by CNMDNC** [comment] 2016-05-26 04:11
same here

**Comment by nickbutcher** [comment] 2016-05-26 13:56
Dupe of #17. This project requires `git` to automate some of the build steps. Please either ensure that you have `git` on your `path` or comment out the relevant sections of `build.gradle`.

**Closed by nickbutcher** 2016-05-26 13:56 UTC

**Comment by fahadshams** [comment] 2017-05-05 09:40
same error is coming here.how solve this problem
