### ISSUE TITLE
CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by Jaydeep00** [nickbutcher/plaid#165] opened 2017-03-06 12:21 UTC

**Comment by nickbutcher** [comment] 2017-03-06 13:30
Please can you provide more info on this issue and steps to reproduce.

**Comment by imneeraj** [comment] 2017-03-14 06:56
I'm also getting the same error while the project is building.
In app/build.gradle :' def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()'

**Comment by nickbutcher** [comment] 2017-03-14 08:40
Building Plaid required `git` on your path. Closing as dupe of #17

**Closed by nickbutcher** 2017-03-14 08:40 UTC
